
#version: '3.9'
services:
  db:
    build:
      context: ./postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - ENV POSTGRES_DB=Favorita
      - ENV POSTGRES_USER=admin
      - ENV POSTGRES_PASSWORD=unsecuredpass
    volumes:
      - db_data:/var/lib/postgresql/data
  client:
    build:
      context: ./client
    container_name: client
    depends_on:
      - db
  app:
    build:
      context: ./streamlitapp
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=Favorita
      - DB_USER=admin
      - DB_PASSWORD=unsecuredpass
volumes:
  db_data: {}